name: 📦 Install
description: Install dependencies

runs:
    using: 'composite'
    steps:
        - name: 🏎️ Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
              bun-version: canary

        - name: Install dependencies
          shell: bash
          run: bun install
